
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eo-portal-reverse-proxy
  namespace: pavedroad
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: eo.pavedroad.io
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: eo-portal
            port:
              number: 80
