
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eo-portal-reverse-proxy
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: eo.pavedroad.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eo-portal
            port:
              number: 8800
