
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eo-portal
spec:
  replicas: 3
  strategy: {}
  selector:
    matchLabels:
      pavedroad.service: eo-portal
  template:
    metadata:
      creationTimestamp: null
      labels:
        pavedroad.service: eo-portal
    spec:
      containers:
      - image: 400276217548.dkr.ecr.us-west-1.amazonaws.com/io.pavedroad.stagging/eo-portal
        name: eo-portal
        ports:
        - containerPort: 8800
        resources: {}
      restartPolicy: Always
