
apiVersion: v1
kind: Service
metadata:
  name: eo-portal
spec:
  ports:
  - name: "8800"
    port: 8800
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    pavedroad.service: eo-portal
  type: NodePort
status:
  loadBalancer: {}
