
apiVersion: v1
kind: Service
metadata:
  name: eo-portal
spec:
  ports:
    - protocol: TCP
      name: "listing-8800-forward-80"
      port: 8800
      targetPort: 80
  selector:
    pavedroad.service: eo-portal
  type: NodePort
status:
  loadBalancer: {}
