
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

bases:
  - eo-portal
  - ingress

commonLabels:
  pavedroad.env: staging

commonAnnotations:
  pavedroad.kustomize.base: eventbridge-ux/manifests/kubernetes/stag
  pavedroad.kustomize.bases: "eo-portal"
