
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pavedroad

bases:
  - eo-portal
  - ingress

resources:
  - namespace.yaml

commonLabels:
  pavedroad.env: stagging

commonAnnotations:
  pavedroad.kustomize.base: eventbridge-ux/manifests/kubernetes/stag
  pavedroad.kustomize.bases: "eo-portal"
