
apiVersion: v1
kind: Service
metadata:
  name: eo-portal
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    pavedroad.service: eo-portal
  type: NodePort
status:
  loadBalancer: {}
