
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pavedroad

bases:
  - eo-portal

resources:
  - namespace.yaml

commonLabels:
  pavedroad.env: dev

commonAnnotations:
  pavedroad.kustomize.base: eventbridge-ux/manifests/kubernetes/dev
  pavedroad.kustomize.bases: "eo-portal"
